name: NixOS

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ${{ github.event.client_payload.runs-on }}

    strategy:
      fail-fast: true

    steps:
      - name: Add mask
        run: |
          REPO=$(jq -r '.client_payload.repository' "${GITHUB_EVENT_PATH}")
          REF=$(jq -r '.client_payload.ref' "${GITHUB_EVENT_PATH}")
          HOST=$(jq -r '.client_payload.hostname' "${GITHUB_EVENT_PATH}")
          GIT_CRYPT_KEY=$(jq -r '.client_payload.git_crypt_key' "${GITHUB_EVENT_PATH}")
          echo "::add-mask::${REPO}"
          echo "::add-mask::${REF}"
          echo "::add-mask::${HOST}"
          [ "${GIT_CRYPT_KEY}" != "null" ] && echo "::add-mask::${GIT_CRYPT_KEY}"

      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.ref }}
          token: ${{ secrets.PAT }}

      - name: "Free disk space for Nix"
        uses: wimpysworld/nothing-but-nix@v10
        with:
          hatchet-protocol: 'cleave' # holster, carve, cleave (default), rampage

      - name: "Install Nix"
        uses: cachix/install-nix-action@v31.8.4
        with:
          extra_nix_config: |
            accept-flake-config = true
            experimental-features = nix-command flakes
            trusted-users = root runner
            trusted-substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.c0d3m4513r.com
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.c0d3m4513r.com:DyXDxkX3kg03nPmwOiX536o2P2rPYY7wHDCbs27xya8=

      - name: Configure Git-Crypt
        run: |
          GIT_CRYPT_KEY=$(jq -r '.client_payload.git_crypt_key' "${GITHUB_EVENT_PATH}")
          [ "${GIT_CRYPT_KEY}" == "null" ] && exit 0
          nix profile add nixpkgs#git-crypt
          echo "${GIT_CRYPT_KEY}" | base64 --decode > key
          git-crypt unlock key
          unlink key

      - name: Add SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh

            ssh-keyscan cache.c0d3m4513r.com >> /home/runner/.ssh/known_hosts

            echo "${{ secrets.CACHE_SSH_KEY }}" > /home/runner/.ssh/github_actions

            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a "${SSH_AUTH_SOCK}" > /dev/null
            ssh-add /home/runner/.ssh/github_actions

      - name: "Build NixOS config"
        run: |
          nix build .#nixosConfigurations.${{ github.event.client_payload.hostname }}.config.system.build.toplevel --print-build-logs --no-update-lock-file

      - name: "Push NixOS config to cache"
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          nix copy --to ssh://nix-ssh@cache.c0d3m4513r.com .#nixosConfigurations.${{ github.event.client_payload.hostname }}.config.system.build.toplevel --print-build-logs --no-update-lock-file
